### ISSUE TITLE
How to use this library with pico?

### ISSUE THREAD

**Issue by samuelleecong** [adamczykpiotr/pico-mcp2515#2]
Hi, I have tried downloading the library and adding it as a zip library, but it is returning me this error. 
<img width="484" alt="image" src="https://user-images.githubusercontent.com/63988139/199383794-e5a5762a-2d12-44f1-b7f0-0f35a9e03c23.png">

Could you advice on how I could go about using your library for the raspberry pi pico? Thanks in advance.

**Comment by adamczykpiotr** [comment]
Hello!

This library is not meant to be used with Arduino IDE but in a CMAKE-built project, like all the examples from https://github.com/raspberrypi/pico-examples 

I'll try to add an example some time in the future as more people might face this issue. Thanks for bringing it to my attention.
